# Generated by Django 3.1.6 on 2021-02-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
